### PR TITLE
Feat: Scheduled playout

### PR DESCRIPTION
**Pull request by nytamin**
This is a **large PR** that adds "Scheduling"-functionality to playout.

To make it work, the implementation touches most of the playout-logic.

Features:

* New property on Group: **Playout Mode**, where Normal is the default (this makes playout work as it does today).
image
* **Scheduled playout**
Image
  * User can select a Start Time
  * User can select various Repeating modes (Daily, Weekly, Monthly or Custom)
* When a Part has started playing from a schedule, user can still Pause, Stop or Play it.
  * To resume a schedule after a stop, click disable then enable schedule.

TODO:

- [x] Test that this doesn't break anything, playout-wise

### CODE REVIEW

**Comment by nytamin** [comment]
@alvancamp If you have time, could you give this a test as your review?

I don't expect a deep dive into the code due to the sheer size of it. (I'm sure the code is perfectly readable, well documented and without any bugs - hah!)

**Comment by alvancamp** [comment]
This is _really_ cool, nice work! I did some surface-level testing and everything seemed okay but I wasn't sure how to test the various `Repeating` modes. I tried changing my system clock and it didn't seem to affect SuperConductor, at least not while it was running. I'm also wondering if an `HOURLY` repeat mode would be useful. For example, there are Twitch streamers that like to run ads every hour on the hour (regardless of what they are showing on stream, lol).

**Review by alvancamp — COMMENTED** [review]
Looking good to me so far, the only confusing thing I'm seeing is some behavior of the "Repeat Until" input. Below are some examples:

1. When entering the string `2022-08-30` and then hitting Enter, the result becomes `2022-08-29 19:00:00`. However, entering `2022-08-30` a second time results in the string staying there with no change.
2. When entering the string `2023` and then hitting Enter, the result becomes `2022-12-31 18:00:00`. Likewise with the above, entering the same value a second time results in it sticking.

**Comment by nytamin** [comment]
Good feedback! I made some improvements to the date-time input parser just now, there might be other formats that i've missed, but we can always fix them later.

**Comment by KevinMikkelsen** [comment]
cool feature. Thanks!
It would be nice if it was possible to schedule more than one start time.

Same date, multiple start times.

**Comment by nytamin** [comment]
Yeah that would be useful! Could you open a separate issue for that feature request please? 🙂

**Pull request merged**
